todolist/urls.py
from django.urls import path, include
from .import views

app_name = 'todolist'
urlpatterns = [
    path('home/', views.home, name='主页'),
    path('about/', views.about, name='关于'),
    path('edit/', views.edit, name='编辑'),
    path('getdata/', views.getdata, name='数据提交'),
    path('serchdata/', views.serchdata, name='数据查询'),
]

todolist/models.py
from django.db import models
from datetime import datetime

class Frank(models.Model):
   class Meta:
       verbose_name = u"FrankWork"
       verbose_name_plural = verbose_name

todolist/views.py
from django.shortcuts import render

# Create your views here.

lst = [
	{'待办事项':'遛狗', '已完成':False},
	{'待办事项':'遛狗', '已完成':True},
]

key = [
	{'开关值':'off'},
]

def home(request):
	global lst
	if request.method == "POST":
		if request.POST['待办事项'] == '':
			return render(request,"todolist/home.html", {'警告': '请输入内容！'})
		else:
			lst.append({'待办事项': request.POST['待办事项'], '已完成':False})
			content = { '清单': lst}
			return render(request,"todolist/home.html", content)
	elif request.method == "GET":
		content = { '清单': lst}
		return render(request,"todolist/home.html", content)

def about(request):
	return render(request,"todolist/about.html")

def edit(request):
	return render(request,"todolist/edit.html")

def serchdata(request):
	content = { '开关值变动': key}
	return render(request,"todolist/serchdata.html", content)

def getdata(request):
	global key
	if request.method == "POST":
		if request.POST['开关值'] == 'on':
			key[0]['开关值'] = request.POST['开关值']
			content = { '开关值变动': key[0]['开关值']}
			return render(request,"todolist/getdata.html", content)
		else:
			key[0]['开关值'] = request.POST['开关值']
			content = { '开关值变动': key[0]['开关值']}
			return render(request,"todolist/getdata.html", content)
	elif request.method == "GET":
		content = { '开关值变动': key}
		return render(request,"todolist/getdata.html", content)

xadmin/views/base.py
import copy
import functools
import datetime
import decimal
from functools import update_wrapper
from inspect import getfullargspec

from django import forms
from django.apps import apps
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_permission_codename
from django.core.exceptions import ValidationError
from django.core.serializers.json import DjangoJSONEncoder
from django.urls.base import reverse
from django.http import HttpResponse
from django.template import Context, Template
from django.template.response import TemplateResponse
from django.utils import six
from django.utils.decorators import method_decorator, classonlymethod
from django.utils.encoding import force_text, smart_text, smart_str
from django.utils.functional import Promise
from django.utils.http import urlencode
from django.utils.itercompat import is_iterable
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from collections import OrderedDict
from xadmin.util import static, json, vendor, sortkeypicker

from xadmin.models import Log

csrf_protect_m = method_decorator(csrf_protect)


class IncorrectPluginArg(Exception):
    pass


def get_content_type_for_model(obj):
    from django.contrib.contenttypes.models import ContentType
    return ContentType.objects.get_for_model(obj, for_concrete_model=False)


def filter_chain(filters, token, func, *args, **kwargs):
    if token == -1:
        return func()
    else:
        def _inner_method():
            fm = filters[token]
            fargs = getfullargspec(fm)[0]
            if len(fargs) == 1:
                # Only self arg
                result = func()
                if result is None:
                    return fm()
                else:
                    raise IncorrectPluginArg(u'Plugin filter method need a arg to receive parent method result.')
            else:
                return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
        return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)


def filter_hook(func):
    tag = func.__name__
    func.__doc__ = "``filter_hook``\n\n" + (func.__doc__ or "")

    @functools.wraps(func)
    def method(self, *args, **kwargs):

        def _inner_method():
            return func(self, *args, **kwargs)

        if self.plugins:
            filters = [(getattr(getattr(p, tag), 'priority', 10), getattr(p, tag))
                       for p in self.plugins if callable(getattr(p, tag, None))]
            filters = [f for p, f in sorted(filters, key=lambda x:x[0])]
            return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
        else:
            return _inner_method()
    return method


def inclusion_tag(file_name, context_class=Context, takes_context=False):
    def wrap(func):
        @functools.wraps(func)
        def method(self, context, nodes, *arg, **kwargs):
            _dict = func(self, context, nodes, *arg, **kwargs)
            from django.template.loader import get_template, select_template
            cls_str = str if six.PY3 else basestring
            if isinstance(file_name, Template):
                t = file_name
            elif not isinstance(file_name, cls_str) and is_iterable(file_name):
                t = select_template(file_name)
            else:
                t = get_template(file_name)

            _dict['autoescape'] = context.autoescape
            _dict['use_l10n'] = context.use_l10n
            _dict['use_tz'] = context.use_tz
            _dict['admin_view'] = context['admin_view']

            csrf_token = context.get('csrf_token', None)
            if csrf_token is not None:
                _dict['csrf_token'] = csrf_token
            nodes.append(t.render(_dict))

        return method
    return wrap


class JSONEncoder(DjangoJSONEncoder):

    def default(self, o):
        if isinstance(o, datetime.datetime):
            return o.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(o, datetime.date):
            return o.strftime('%Y-%m-%d')
        elif isinstance(o, decimal.Decimal):
            return str(o)
        elif isinstance(o, Promise):
            return force_text(o)
        else:
            try:
                return super(JSONEncoder, self).default(o)
            except Exception:
                return smart_text(o)


class BaseAdminObject(object):

    def get_view(self, view_class, option_class=None, *args, **kwargs):
        opts = kwargs.pop('opts', {})
        return self.admin_site.get_view_class(view_class, option_class, **opts)(self.request, *args, **kwargs)

    def get_model_view(self, view_class, model, *args, **kwargs):
        return self.get_view(view_class, self.admin_site._registry.get(model), *args, **kwargs)

    def get_admin_url(self, name, *args, **kwargs):
        return reverse('%s:%s' % (self.admin_site.app_name, name), args=args, kwargs=kwargs)

    def get_model_url(self, model, name, *args, **kwargs):
        return reverse(
            '%s:%s_%s_%s' % (self.admin_site.app_name, model._meta.app_label,
                             model._meta.model_name, name),
            args=args, kwargs=kwargs, current_app=self.admin_site.name)

    def get_model_perm(self, model, name):
        return '%s.%s_%s' % (model._meta.app_label, name, model._meta.model_name)

    def has_model_perm(self, model, name, user=None):
        user = user or self.user
        return user.has_perm(self.get_model_perm(model, name)) or (name == 'view' and self.has_model_perm(model, 'change', user))

    def get_query_string(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return '?%s' % urlencode(p)

    def get_form_params(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return mark_safe(''.join(
            '<input type="hidden" name="%s" value="%s"/>' % (k, v) for k, v in p.items() if v))

    def render_response(self, content, response_type='json'):
        if response_type == 'json':
            response = HttpResponse(content_type="application/json; charset=UTF-8")
            response.write(
                json.dumps(content, cls=JSONEncoder, ensure_ascii=False))
            return response
        return HttpResponse(content)

    def template_response(self, template, context):
        return TemplateResponse(self.request, template, context)

    def message_user(self, message, level='info'):
        """
        Send a message to the user. The default implementation
        posts a message using the django.contrib.messages backend.
        """
        if hasattr(messages, level) and callable(getattr(messages, level)):
            getattr(messages, level)(self.request, message)

    def static(self, path):
        return static(path)

    def vendor(self, *tags):
        return vendor(*tags)

    def log(self, flag, message, obj=None):
        log = Log(
            user=self.user,
            ip_addr=self.request.META['REMOTE_ADDR'],
            action_flag=flag,
            message=message
        )
        if obj:
            log.content_type = get_content_type_for_model(obj)
            log.object_id = obj.pk
            log.object_repr = force_text(obj)
        log.save()


class BaseAdminPlugin(BaseAdminObject):

    def __init__(self, admin_view):
        self.admin_view = admin_view
        self.admin_site = admin_view.admin_site

        if hasattr(admin_view, 'model'):
            self.model = admin_view.model
            self.opts = admin_view.model._meta

    def init_request(self, *args, **kwargs):
        pass


class BaseAdminView(BaseAdminObject, View):
    """ Base Admin view, support some comm attrs."""

    base_template = 'xadmin/base.html'
    need_site_permission = True

    def __init__(self, request, *args, **kwargs):
        self.request = request
        self.request_method = request.method.lower()
        self.user = request.user

        self.base_plugins = [p(self) for p in getattr(self,
                                                      "plugin_classes", [])]

        self.args = args
        self.kwargs = kwargs
        self.init_plugin(*args, **kwargs)
        self.init_request(*args, **kwargs)

    @classonlymethod
    def as_view(cls):
        def view(request, *args, **kwargs):
            self = cls(request, *args, **kwargs)

            if hasattr(self, 'get') and not hasattr(self, 'head'):
                self.head = self.get

            if self.request_method in self.http_method_names:
                handler = getattr(
                    self, self.request_method, self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed

            return handler(request, *args, **kwargs)

        # take name and docstring from class
        update_wrapper(view, cls, updated=())
        view.need_site_permission = cls.need_site_permission

        return view

todolist/templates/todolist/about.html
{% extends "todolist/base.html" %}
{% block 标题 %}关于{% endblock 标题 %}
{% block 关于高亮 %}active{% endblock 关于高亮 %}
{% block 主体 %}
<br>
<h4>一款小巧、间接的代办清单工具</h4>
{% endblock 主体 %}

todolist/templates/todolist/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>{% block 标题 %}{% endblock 标题 %}</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/navbar-static/">

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link rel="stylesheet" type="text/css" href="{% static '/todolist/css/base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% block css%}{% endblock css%}">
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4" id = "topnav">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item {% block 主页高亮 %}{% endblock 主页高亮 %}">
            <a class="nav-link" href="{% url 'todolist:主页' %}">待办清单</a>
          </li>
          <li class="nav-item {% block 关于高亮 %}{% endblock 关于高亮 %}">
            <a class="nav-link" href="{% url 'todolist:关于' %}">关于本站</a>
          </li>
        </ul>
        <form class="form-inline mt-2 mt-md-0 col-7 justify-content-end " method="POST" action="">
          {% csrf_token %}
          <input name="待办事项" class="form-control mr-sm-2" type="text" placeholder="待办事项" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">添加</button>
        </form>
      </div>
    </nav>
    <main role="main" class="container">
      {% block 主体 %}
      {% endblock 主体 %}
    </main>
    <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.bootcss.com/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.bootcss.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <!--Sparkline Charts Needed Scripts-->
    <script src="https://cdn.bootcss.com/Chart.js/2.8.0/Chart.bundle.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.bundle.js"></script>
    
  </body>
</html>

todolist/templates/todolist/edit.html
{% extends "todolist/base.html" %}

{% load static %}

{% block css %}{% static '/todolist/css/edit.css' %}{% endblock css %}

{% block 标题 %}待办事项提交{% endblock 标题 %}
{% block 主体 %}
<br>
<form id="form-edit">
  <div class="form-group">
    <label for="editTodo"></label>
    <input class="form-control form-control-lg" id="editTodo" type="text" value="遛狗">
    <small id="help" class="form-text text-muted">在这里编辑代办事项</small>
  </div>
  <button type="button" class="btn btn-primary btn-lg btn-block">提交</button>
</form>
{% endblock 主体 %}

todolist/templates/todolist/getdata.html
{% extends "todolist/base.html" %}
{% block 标题 %}硬件直播控制平台{% endblock 标题 %}
{% block 关于高亮 %}active{% endblock 关于高亮 %}
{% block 主体 %}

<h1>硬件直播控制平台</h1>
<br>
<br>
<!-- strobe -->
<script type="text/javascript" src="strobe/lib/swfobject.js"></script>
<script type="text/javascript">
  var parameters = {  
     src: "rtmp://{pi_address}/rtmp/live",  
     autoPlay: false,  
     controlBarAutoHide: false,  
     playButtonOverlay: true,  
     showVideoInfoOverlayOnStartUp: true,  
     optimizeBuffering : false,  
     initialBufferTime : 0.1,  
     expandedBufferTime : 0.1,  
     minContinuousPlayback : 0.1,  
     poster: "images/poster.png"  
  };  
  swfobject.embedSWF(
    "strobe/StrobeMediaPlayback.swf"
    , "StrobeMediaPlayback"
    , 1024
    , 768
    , "10.1.0"
    , "strobe/expressInstall.swf"
    , parameters
    , {
      allowFullScreen: "true"
    }
    , {
      name: "StrobeMediaPlayback"
    }
  );
</script>
 
</head>
<body>
  <br>
  <br>
  <div>
    <h3>远程开关灯控制当前状态：{{ 开关值变动 }}</h3>
    <form class="form-inline mt-2 mt-md-0 col-7 justify-content-end " method="POST" action="">
          {% csrf_token %}
          <input name="开关值" value="on" class="form-control mr-sm-0" type="hidden" placeholder="待办事项12" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">ON</button>
    </form>
    <form class="form-inline mt-2 mt-md-0 col-7 justify-content-end " method="POST" action="">
          {% csrf_token %}
          <input name="开关值" value="off" class="form-control mr-sm-0" type="hidden" placeholder="待办事项12" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">OFF</button>
    </form>
  </div>
  <br>
  <br>
  <div>
    <h1>Charm</h1>
    
  </div>
</body>
</html>
{% endblock 主体 %}

todolist/templates/todolist/home.html
{% extends "todolist/base.html" %}

{% load static %}

{% block css %}{% static '/todolist/css/home.css' %}{% endblock css %}

{% block 标题 %}个人代办清单{% endblock 标题 %}
{% block 主页高亮 %}active{% endblock 主页高亮 %}
{% block 主体 %}
{{警告}}
<br>
<div class="table-responsive">
  <table class="table table-hover">
    <thead class="thead-light">
      <tr>
        <th>序号</th>
        <th>待办事项</th>
        <th>编辑</th>
        <th>划掉</th>
        <th>删除</th>
      </tr>
    </thead>
    <tbody class="no-underline">
      {% for 每一件事 in 清单 %}
        {% if 每一件事.已完成 %}
          <tr class="table-dark">
            <th class="text-dark" scope="row">{{ forloop.counter }}</th>
            <td class="text-dark" id="line-through">{{ 每一件事.待办事项 }}</td>
            <td class="text-secondary">不可编辑</td>
            <td><a class="text-info" href="#">撤销</a></td>
            <td ><a class="text-danger" href="#">删除</a></td>
          </tr>
        {% else %}
          <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ 每一件事.待办事项 }}</td>
            <td ><a class="text-success" href="{% url 'todolist:编辑' %}">编辑</a></td>
            <td ><a href="#">划掉</a></td>
            <td><a class="text-info" href="#">删除</a></td>
          </tr>
        {% endif %}
      {% endfor %}

     <!--  
      <tr>
        <th scope="row">2</th>
        <td>看书</td>
        <td ><a class="text-success" href="#">编辑</a></td>
        <td ><a href="#">划掉</a></td>
        <td><a class="text-info" href="#">删除</a></td>
      </tr>
      <tr>
        <th scope="row">3</th>
        <td>散步</td>
        <td ><a class="text-success" href="#">编辑</a></td>
        <td ><a href="#">划掉</a></td>
        <td><a class="text-info" href="#">删除</a></td>
      </tr>
      <tr class="table-dark">
        <th class="text-dark" scope="row">4</th>
        <td class="text-dark" id="line-through">去超市</td>
        <td class="text-secondary">不可编辑</td>
        <td><a class="text-info" href="#">撤销</a></td>
        <td ><a class="text-danger" href="#">删除</a></td>
      </tr> -->
    </tbody>
  </table>
</div>
{% endblock 主体 %}

todolist/templates/todolist/serchdata.html
{{ 开关值变动 }}